@root_url=http://localhost:19000

GET {{root_url}}/one
###
GET {{root_url}}/two
###
GET {{root_url}}/three
###
GET {{root_url}}/four
###
GET {{root_url}}/five
###
GET {{root_url}}/six
###
GET {{root_url}}/seven
###
GET {{root_url}}/eight
###
GET {{root_url}}/nine
###
GET {{root_url}}/ten
###
GET {{root_url}}/eleven
###
GET {{root_url}}/twelve
###
GET {{root_url}}/thirteen
###
GET {{root_url}}/fourteen
###
GET {{root_url}}/fifteen
###
GET {{root_url}}/sixteen
###
GET {{root_url}}/seventeen
###
GET {{root_url}}/eighteen
###
GET {{root_url}}/nineteen
###
GET {{root_url}}/twenty
###
GET {{root_url}}/twentyone
###
GET {{root_url}}/twentytwo
###
GET {{root_url}}/twentythree
###
GET {{root_url}}/twentyfour
Accept: text/event-stream